<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-C35QMNU" ignored="1" name="Default test(failed)" tests="2" failures="1" timestamp="29 Apr 2020 21:37:24 GMT" time="0.053" errors="0">
  <testcase name="test3" time="0.0" classname="testng.TestNgRetryFailed">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testng.TestNgRetryFailed.test3(TestNgRetryFailed.java:23)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test2" time="0.0" classname="testng.TestNgRetryFailed"/>
  <testcase name="test1" time="0.0" classname="testng.TestNgRetryFailed">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
